### ISSUE TITLE
memory saving measurement

### ISSUE THREAD

**Issue by LYX-SOUL** [xiezhq-hermann/graphiler#12]
Hi! Thanks for your impressive work, this work is amazing!
I would like to ask how to measure memory savings, can you elaborate on the method? (e.g. what tool or command to use)
Thank you！

**Comment by xiezhq-hermann** [comment]
> 

Hi, you can take a look at APIs list here to measure GPU memory usage:
https://pytorch.org/docs/stable/generated/torch.cuda.memory_stats.html#torch.cuda.memory_stats
